[tool.poetry]
name = "домашка-1-по-джанго"
version = "0.1.0"
description = "Создание страниц"
authors = ["Алексей"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
flask = "^3.1.2"
requests = "^2.32.5"


[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
black = "^25.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
